import type { AcademicChapter, AcademicSubject, SubjectSlug } from './types'

const chapter = (
  slug: string,
  name: string,
  order: number,
  examTags: AcademicChapter['examTags'] = ['BOARDS', 'JEE_MAIN', 'JEE_ADVANCED'],
): AcademicChapter => ({
  id: slug,
  slug,
  name,
  order,
  topics: [],
  examTags,
})

const boardChapter = (slug: string, name: string, order: number) =>
  chapter(slug, name, order, ['BOARDS'])

const subjects: AcademicSubject[] = [
  {
    id: 'cbse-11-physics',
    slug: 'physics',
    name: 'Physics',
    shortName: 'Physics',
    classLevel: '11',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      chapter('units-and-measurements', 'Units and Measurements', 1),
      chapter('motion-in-a-straight-line', 'Motion in a Straight Line', 2),
      chapter('motion-in-a-plane', 'Motion in a Plane', 3),
      chapter('laws-of-motion', 'Laws of Motion', 4),
      chapter('work-energy-and-power', 'Work, Energy and Power', 5),
      chapter('system-of-particles-and-rotational-motion', 'System of Particles and Rotational Motion', 6),
      chapter('gravitation', 'Gravitation', 7),
      chapter('mechanical-properties-of-solids', 'Mechanical Properties of Solids', 8),
      chapter('mechanical-properties-of-fluids', 'Mechanical Properties of Fluids', 9),
      chapter('thermal-properties-of-matter', 'Thermal Properties of Matter', 10),
      chapter('thermodynamics', 'Thermodynamics', 11),
      chapter('kinetic-theory', 'Kinetic Theory', 12),
      chapter('oscillations', 'Oscillations', 13),
      chapter('waves', 'Waves', 14),
    ],
  },
  {
    id: 'cbse-11-chemistry',
    slug: 'chemistry',
    name: 'Chemistry',
    shortName: 'Chemistry',
    classLevel: '11',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      chapter('some-basic-concepts-of-chemistry', 'Some Basic Concepts of Chemistry', 1),
      chapter('structure-of-atom', 'Structure of Atom', 2),
      chapter('classification-of-elements-and-periodicity', 'Classification of Elements and Periodicity in Properties', 3),
      chapter('chemical-bonding-and-molecular-structure', 'Chemical Bonding and Molecular Structure', 4),
      chapter('chemical-thermodynamics', 'Chemical Thermodynamics', 5),
      chapter('equilibrium', 'Equilibrium', 6),
      chapter('redox-reactions', 'Redox Reactions', 7),
      chapter('organic-chemistry-basic-principles', 'Organic Chemistry: Some Basic Principles and Techniques', 8),
      chapter('hydrocarbons', 'Hydrocarbons', 9),
    ],
  },
  {
    id: 'cbse-11-mathematics',
    slug: 'mathematics',
    name: 'Mathematics',
    shortName: 'Maths',
    classLevel: '11',
    board: 'CBSE',
    streamTags: ['PCM', 'PCMB'],
    chapters: [
      chapter('sets', 'Sets', 1),
      chapter('relations-and-functions', 'Relations and Functions', 2),
      chapter('trigonometric-functions', 'Trigonometric Functions', 3),
      chapter('complex-numbers-and-quadratic-equations', 'Complex Numbers and Quadratic Equations', 4),
      chapter('linear-inequalities', 'Linear Inequalities', 5),
      chapter('permutations-and-combinations', 'Permutations and Combinations', 6),
      chapter('binomial-theorem', 'Binomial Theorem', 7),
      chapter('sequences-and-series', 'Sequences and Series', 8),
      chapter('straight-lines', 'Straight Lines', 9),
      chapter('conic-sections', 'Conic Sections', 10),
      chapter('introduction-to-three-dimensional-geometry', 'Introduction to Three-dimensional Geometry', 11),
      chapter('limits-and-derivatives', 'Limits and Derivatives', 12),
      chapter('statistics', 'Statistics', 13),
      chapter('probability', 'Probability', 14),
    ],
  },
  {
    id: 'cbse-11-biology',
    slug: 'biology',
    name: 'Biology',
    shortName: 'Biology',
    classLevel: '11',
    board: 'CBSE',
    streamTags: ['PCB', 'PCMB'],
    chapters: [
      boardChapter('the-living-world', 'The Living World', 1),
      boardChapter('biological-classification', 'Biological Classification', 2),
      boardChapter('plant-kingdom', 'Plant Kingdom', 3),
      boardChapter('animal-kingdom', 'Animal Kingdom', 4),
      boardChapter('morphology-of-flowering-plants', 'Morphology of Flowering Plants', 5),
      boardChapter('anatomy-of-flowering-plants', 'Anatomy of Flowering Plants', 6),
      boardChapter('structural-organisation-in-animals', 'Structural Organisation in Animals', 7),
      boardChapter('cell-the-unit-of-life', 'Cell: The Unit of Life', 8),
      boardChapter('biomolecules-11', 'Biomolecules', 9),
      boardChapter('cell-cycle-and-cell-division', 'Cell Cycle and Cell Division', 10),
      boardChapter('photosynthesis-in-higher-plants', 'Photosynthesis in Higher Plants', 11),
      boardChapter('respiration-in-plants', 'Respiration in Plants', 12),
      boardChapter('plant-growth-and-development', 'Plant Growth and Development', 13),
      boardChapter('breathing-and-exchange-of-gases', 'Breathing and Exchange of Gases', 14),
      boardChapter('body-fluids-and-circulation', 'Body Fluids and Circulation', 15),
      boardChapter('excretory-products-and-elimination', 'Excretory Products and their Elimination', 16),
      boardChapter('locomotion-and-movement', 'Locomotion and Movement', 17),
      boardChapter('neural-control-and-coordination', 'Neural Control and Coordination', 18),
      boardChapter('chemical-coordination-and-integration', 'Chemical Coordination and Integration', 19),
    ],
  },
  {
    id: 'cbse-11-english',
    slug: 'english',
    name: 'English Core',
    shortName: 'English',
    classLevel: '11',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      boardChapter('reading-skills-11', 'Reading Skills', 1),
      boardChapter('grammar-and-creative-writing-11', 'Grammar and Creative Writing Skills', 2),
      boardChapter('hornbill-prose', 'Hornbill · Prose', 3),
      boardChapter('hornbill-poetry', 'Hornbill · Poetry', 4),
      boardChapter('snapshots-supplementary-reader', 'Snapshots · Supplementary Reader', 5),
    ],
  },
  {
    id: 'cbse-12-physics',
    slug: 'physics',
    name: 'Physics',
    shortName: 'Physics',
    classLevel: '12',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      chapter('electric-charges-and-fields', 'Electric Charges and Fields', 1),
      chapter('electrostatic-potential-and-capacitance', 'Electrostatic Potential and Capacitance', 2),
      chapter('current-electricity', 'Current Electricity', 3),
      chapter('moving-charges-and-magnetism', 'Moving Charges and Magnetism', 4),
      chapter('magnetism-and-matter', 'Magnetism and Matter', 5),
      chapter('electromagnetic-induction', 'Electromagnetic Induction', 6),
      chapter('alternating-current', 'Alternating Current', 7),
      chapter('electromagnetic-waves', 'Electromagnetic Waves', 8),
      chapter('ray-optics-and-optical-instruments', 'Ray Optics and Optical Instruments', 9),
      chapter('wave-optics', 'Wave Optics', 10),
      chapter('dual-nature-of-radiation-and-matter', 'Dual Nature of Radiation and Matter', 11),
      chapter('atoms', 'Atoms', 12),
      chapter('nuclei', 'Nuclei', 13),
      chapter('semiconductor-electronics', 'Semiconductor Electronics', 14),
    ],
  },
  {
    id: 'cbse-12-chemistry',
    slug: 'chemistry',
    name: 'Chemistry',
    shortName: 'Chemistry',
    classLevel: '12',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      chapter('solutions', 'Solutions', 1),
      chapter('electrochemistry', 'Electrochemistry', 2),
      chapter('chemical-kinetics', 'Chemical Kinetics', 3),
      chapter('d-and-f-block-elements', 'The d- and f-Block Elements', 4),
      chapter('coordination-compounds', 'Coordination Compounds', 5),
      chapter('haloalkanes-and-haloarenes', 'Haloalkanes and Haloarenes', 6),
      chapter('alcohols-phenols-and-ethers', 'Alcohols, Phenols and Ethers', 7),
      chapter('aldehydes-ketones-and-carboxylic-acids', 'Aldehydes, Ketones and Carboxylic Acids', 8),
      chapter('amines', 'Amines', 9),
      chapter('biomolecules', 'Biomolecules', 10),
    ],
  },
  {
    id: 'cbse-12-mathematics',
    slug: 'mathematics',
    name: 'Mathematics',
    shortName: 'Maths',
    classLevel: '12',
    board: 'CBSE',
    streamTags: ['PCM', 'PCMB'],
    chapters: [
      chapter('relations-and-functions-12', 'Relations and Functions', 1),
      chapter('inverse-trigonometric-functions', 'Inverse Trigonometric Functions', 2),
      chapter('matrices', 'Matrices', 3),
      chapter('determinants', 'Determinants', 4),
      chapter('continuity-and-differentiability', 'Continuity and Differentiability', 5),
      chapter('applications-of-derivatives', 'Applications of Derivatives', 6),
      chapter('integrals', 'Integrals', 7),
      chapter('applications-of-integrals', 'Applications of Integrals', 8),
      chapter('differential-equations', 'Differential Equations', 9),
      chapter('vector-algebra', 'Vector Algebra', 10),
      chapter('three-dimensional-geometry', 'Three-dimensional Geometry', 11),
      chapter('linear-programming', 'Linear Programming', 12, ['BOARDS']),
      chapter('probability-12', 'Probability', 13),
    ],
  },
  {
    id: 'cbse-12-biology',
    slug: 'biology',
    name: 'Biology',
    shortName: 'Biology',
    classLevel: '12',
    board: 'CBSE',
    streamTags: ['PCB', 'PCMB'],
    chapters: [
      boardChapter('sexual-reproduction-in-flowering-plants', 'Sexual Reproduction in Flowering Plants', 1),
      boardChapter('human-reproduction', 'Human Reproduction', 2),
      boardChapter('reproductive-health', 'Reproductive Health', 3),
      boardChapter('principles-of-inheritance-and-variation', 'Principles of Inheritance and Variation', 4),
      boardChapter('molecular-basis-of-inheritance', 'Molecular Basis of Inheritance', 5),
      boardChapter('evolution', 'Evolution', 6),
      boardChapter('human-health-and-disease', 'Human Health and Disease', 7),
      boardChapter('microbes-in-human-welfare', 'Microbes in Human Welfare', 8),
      boardChapter('biotechnology-principles-and-processes', 'Biotechnology: Principles and Processes', 9),
      boardChapter('biotechnology-and-its-applications', 'Biotechnology and its Applications', 10),
      boardChapter('organisms-and-populations', 'Organisms and Populations', 11),
      boardChapter('ecosystem', 'Ecosystem', 12),
      boardChapter('biodiversity-and-conservation', 'Biodiversity and Conservation', 13),
    ],
  },
  {
    id: 'cbse-12-english',
    slug: 'english',
    name: 'English Core',
    shortName: 'English',
    classLevel: '12',
    board: 'CBSE',
    streamTags: ['PCM', 'PCB', 'PCMB'],
    chapters: [
      boardChapter('reading-skills-12', 'Reading Skills', 1),
      boardChapter('creative-writing-skills-12', 'Creative Writing Skills', 2),
      boardChapter('flamingo-prose', 'Flamingo · Prose', 3),
      boardChapter('flamingo-poetry', 'Flamingo · Poetry', 4),
      boardChapter('vistas-supplementary-reader', 'Vistas · Supplementary Reader', 5),
    ],
  },
]

export function getCurriculumSubjects(classLevel: '11' | '12', subjectSlugs?: SubjectSlug[]) {
  return subjects.filter(
    (subject) => subject.classLevel === classLevel && (!subjectSlugs || subjectSlugs.includes(subject.slug)),
  )
}

export function getCurriculumSubject(classLevel: '11' | '12', subjectSlug: string) {
  return subjects.find((subject) => subject.classLevel === classLevel && subject.slug === subjectSlug) ?? null
}

export function getCurriculumChapter(
  classLevel: '11' | '12',
  subjectSlug: string,
  chapterSlug: string,
) {
  const subject = getCurriculumSubject(classLevel, subjectSlug)
  if (!subject) return null
  return subject.chapters.find((item) => item.slug === chapterSlug) ?? null
}

export const curriculumMetadata = {
  board: 'CBSE' as const,
  academicYear: '2026-27',
  sourcePolicy:
    'Structured curriculum metadata follows the current CBSE Senior Secondary subject catalogue; learning explanations must be original and resources must be verified before publishing.',
}
