import type { Metadata } from 'next'
import { PublicPageShell } from '@/components/marketing/public-page-shell'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export const metadata: Metadata = {
  title: 'Terms of Use · Lernio AI',
  description: 'The terms under which you may use Lernio.',
}

export default async function TermsPage() {
  const session = await getServerSession(authOptions)
  return (
    <PublicPageShell isAuthenticated={Boolean(session?.user)}>
      <article className="marketing-container py-12 md:py-16">
        <div className="prose prose-sm max-w-2xl dark:prose-invert">
          <h1>Terms of Use</h1>
          <p className="text-muted-foreground">
            Last updated: {new Date().getFullYear()}
          </p>

          <h2>Acceptable use</h2>
          <ul>
            <li>Use Lernio only for legitimate study and revision.</li>
            <li>Do not attempt to forge scores, XP or achievements.</li>
            <li>Do not attempt to access another user&rsquo;s data.</li>
            <li>Do not abuse, reverse-engineer or overload the service.</li>
          </ul>

          <h2>Accounts</h2>
          <p>
            You are responsible for keeping your password secure. Students can
            create accounts directly; staff roles require an invite code
            issued by an existing administrator. You must not share your
            account or invite codes with others.
          </p>

          <h2>Content</h2>
          <p>
            Lesson content is authored by Lernio contributors and reviewed
            before publication. Contributions (notes, materials) you submit
            are moderated. You retain ownership of your submissions and grant
            Lernio a licence to host and display them within the platform.
          </p>

          <h2>AI Tutor</h2>
          <p>
            AI Tutor answers are generated by a language model using approved
            Lernio lessons as grounding. They are study aids, not a substitute
            for verified academic instruction. Always cross-check important
            answers with your teacher or textbook.
          </p>

          <h2>Coding Lab</h2>
          <p>
            The Coding Lab is a syntax-learning playground. It does not
            compile or execute C++ code. Any &ldquo;Run&rdquo; action performs
            local syntax checks only.
          </p>

          <h2>Limitation of liability</h2>
          <p>
            Lernio is provided &ldquo;as is&rdquo; without warranty of any
            kind. We are not liable for any loss arising from the use of the
            platform, including but not limited to lost study time or exam
            outcomes.
          </p>

          <h2>Contact</h2>
          <p>
            Questions about these terms? Email{' '}
            <a href="mailto:support@lernio.ai">support@lernio.ai</a>.
          </p>
        </div>
      </article>
    </PublicPageShell>
  )
}
